export const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES_MAP: 'category/SET_CATEGORIES_MAP',
    SET_CATEGORIES_MEALS: 'category/SET_CATEGORIES_MEALS',
    UPDATE_CATEGORIES_WEIGHT: 'category/UPDATE_CATEGORIES_WEIGHT',
    UPDATE_CATEGORIES_HEIGHT: 'category/UPDATE_CATEGORIES_HEIGHT',
    UPDATE_CATEGORIES_AGE: 'category/UPDATE_CATEGORIES_AGE',
    UPDATE_CATEGORIES_ACTIVITYLEVEL: 'category/UPDATE_CATEGORIES_ACTIVITYLEVEL',
    UPDATE_CATEGORIES_GOAL: 'category/UPDATE_CATEGORIES_GOAL',
}